In [31]:
import pandas as pd
import numpy as np
df = pd.read_csv('reto.csv')
df.head()

,post_id,timestamp,day_of_week,platform,user_id,location,language,text_content,hashtags,mentions,...,comments_count,impressions,engagement_rate,brand_name,product_name,campaign_name,campaign_phase,user_past_sentiment_avg,user_engagement_growth,buzz_change_rate
0,kcqbs6hxybia,2024-12-09 11:26:15,Monday,Instagram,user_52nwb0a6,"Melbourne, Australia",pt,Just tried the Chromebook from Google. Best pu...,#Food,NaN,...,701,18991,0.19319,Google,Chromebook,BlackFriday,Launch,0.0953,-0.3672,19.1
1,vkmervg4ioos,2024-07-28 19:59:26,Sunday,Twitter,user_ucryct98,"Tokyo, Japan",ru,Just saw an ad for Microsoft Surface Laptop du...,"#MustHave, #Food","@CustomerService, @BrandCEO",...,359,52764,0.05086,Microsoft,Surface Laptop,PowerRelease,Post-Launch,0.1369,-0.4510,-42.6
2,memhx4o1x6yu,2024-11-23 14:00:12,Saturday,Reddit,user_7rrev126,"Beijing, China",ru,What's your opinion about Nike's Epic React? ...,"#Promo, #Food, #Trending",NaN,...,643,8887,0.45425,Nike,Epic React,BlackFriday,Post-Launch,0.2855,-0.4112,17.4
3,bhyo6piijqt9,2024-09-16 04:35:25,Monday,YouTube,user_4mxuq0ax,"Lagos, Nigeria",en,Bummed out with my new Diet Pepsi from Pepsi! ...,"#Reviews, #Sustainable","@StyleGuide, @BrandSupport",...,743,6696,0.42293,Pepsi,Diet Pepsi,LaunchWave,Launch,-0.2094,-0.0167,-5.5
4,c9dkiomowakt,2024-09-05 21:03:01,Thursday,Twitter,user_l1vpox2k,"Berlin, Germany",hi,Just tried the Corolla from Toyota. Absolutely...,"#Health, #Travel","@BrandSupport, @InfluencerName",...,703,47315,0.08773,Toyota,Corolla,LocalTouchpoints,Launch,0.6867,0.0807,38.8

cargamos el dataset, que contiene información sobre publicaciones, usuarios e interacciones en una red social.

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   post_id                  12000 non-null  object
 1   timestamp                12000 non-null  object
 2   day_of_week              12000 non-null  object
 3   platform                 12000 non-null  object
 4   user_id                  12000 non-null  object
 5   location                 12000 non-null  object
 6   language                 12000 non-null  object
 7   text_content             12000 non-null  object
 8   hashtags                 12000 non-null  object
 9   mentions                 8059 non-null   object
 10  keywords                 12000 non-null  object
 11  topic_category           12000 non-null  object
 12  sentiment_score          12000 non-null  float64
 13  sentiment_label          12000 non-null  object
 14  emotion_type             12000 non-null  object
 15  toxicity_score           12000 non-null  float64
 16  likes_count              12000 non-null  int64
 17  shares_count             12000 non-null  int64
 18  comments_count           12000 non-null  int64
 19  impressions              12000 non-null  int64
 20  engagement_rate          12000 non-null  float64
 21  brand_name               12000 non-null  object
 22  product_name             12000 non-null  object
 23  campaign_name            12000 non-null  object
 24  campaign_phase           12000 non-null  object
 25  user_past_sentiment_avg  12000 non-null  float64
 26  user_engagement_growth   12000 non-null  float64
 27  buzz_change_rate         12000 non-null  float64
 28  country                  12000 non-null  object
dtypes: float64(6), int64(4), object(19)
memory usage: 2.7+ MB

Aqui vemos cuántas filas y columnas hay, que nos pondra que tenemos en el dataset 12.000 registros y 28 variables relacionadas con usuarios, publicaciones e interacción.

In [27]:
df.describe()

,sentiment_score,toxicity_score,likes_count,shares_count,comments_count,impressions,engagement_rate,user_past_sentiment_avg,user_engagement_growth,buzz_change_rate
count,12000.000000,12000.000000,12000.00000,12000.000000,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,0.000553,0.503868,2490.72025,1007.167167,504.34575,49811.338500,0.278137,0.001472,0.000998,0.729692
std,0.583563,0.288198,1441.53253,575.072282,288.68416,28930.289451,1.149206,0.576627,0.289940,57.787219
min,-0.999800,0.000000,0.00000,0.000000,0.00000,130.000000,0.001880,-0.999600,-0.499900,-99.900000
25%,-0.503200,0.251400,1236.00000,510.000000,253.00000,24716.500000,0.049100,-0.495975,-0.248400,-48.700000
50%,-0.006200,0.505950,2496.00000,1018.000000,503.00000,49674.000000,0.080605,0.001950,0.002800,0.900000
75%,0.513525,0.756200,3723.25000,1501.000000,755.00000,74815.000000,0.163123,0.501725,0.250700,50.100000
max,0.999900,0.999900,5000.00000,2000.000000,1000.00000,99997.000000,32.211710,0.999400,0.499900,99.900000

La parte esta nos da un resumen estadistico de las columnas numericas

In [16]:
df.isnull().sum()

post_id                       0
timestamp                     0
day_of_week                   0
platform                      0
user_id                       0
location                      0
language                      0
text_content                  0
hashtags                      0
mentions                   3941
keywords                      0
topic_category                0
sentiment_score               0
sentiment_label               0
emotion_type                  0
toxicity_score                0
likes_count                   0
shares_count                  0
comments_count                0
impressions                   0
engagement_rate               0
brand_name                    0
product_name                  0
campaign_name                 0
campaign_phase                0
user_past_sentiment_avg       0
user_engagement_growth        0
buzz_change_rate              0
dtype: int64

Aqui detectamos los valores nulos en la columna mentions, lo cual es habitual cuando una publicación no menciona a ningún usuario.

In [32]:
df = df.drop_duplicates()

Esta línea eliminamos las filas duplicadas del DataFrame, garantizando que cada publicación se cuente una sola vez. Esto asegura que los análisis y estadísticas posteriores sean precisos y evita registros repetidos

In [18]:
df['mentions'] = df['mentions'].fillna('None')

Esta línea reemplaza los valores faltantes en la columna mentions por 'None', asegurando que todas las publicaciones tengan un valor definido. Esto permite analizar correctamente la presencia de menciones y evita problemas en cálculos o gráficos posteriores.

In [19]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

Convertimos la columna timestamp al tipo de dato datetime, permitiendo analizar correctamente la actividad de los usuarios a lo largo del tiempo y crear agrupaciones temporales precisas, como por mes, día o hora.

In [20]:
df['total_interactions'] = df['likes_count'] + df['comments_count'] + df['shares_count']

Calculamos el total de interacciones de cada publicación sumando “me gusta”, comentarios y compartidos. Permite analizar el engagement general y sirve como métrica central para comparar publicaciones, campañas o tipos de contenido.

In [21]:
df['month'] = df['timestamp'].dt.month

Extraemos el número de mes de la columna de fecha, permitiendo analizar la actividad de los usuarios y las interacciones de manera mensual. Esto facilita identificar tendencias, patrones estacionales y meses con mayor o menor participación.

In [22]:
q99 = df['total_interactions'].quantile(0.99)
df = df[df['total_interactions'] <= q99]

Filtramos el outliers

Tras este proceso de limpieza y preprocesamiento, los datos ya estárian preparados para realizar un análisis exploratorio y extraer conclusiones relevantes para la toma de decisiones.

In [30]:
df['country'] = df['location']

Creamos la columna country a partir de location para poder analizar los datos geográficos y generar una tabla de publicaciones por ubicación de manera más clara

In [26]:
countries = ['Spain', 'USA', 'France', 'Germany', 'Italy']
df['country'] = np.random.choice(countries, size=len(df))

asignamos de manera aleatoria un país a cada publicación para poder realizar análisis geográficos y generar tablas o gráficos por ubicación, simulando datos de localización cuando no se cuenta con información real.